version: '3.7'
services:
  sample:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    networks:
      - mynetwork
    environment:
      CHOKIDAR_USEPOLLING: true
      REACT_APP_SERVICEWEB_NETFLIX_COMPTE: "http://0.0.0.0:8090"
      REACT_APP_SERVICEWEB_NETFLIX_POSTER: "http://0.0.0.0:8091"
      REACT_APP_SERVICEWEB_NETFLIX_MEDIA: "http://0.0.0.0:8092"
networks:
  mynetwork:
    name: "mynetwork"